//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class univ_semester_master
    {
        public int univ_semester_id { get; set; }
        public int univ_id { get; set; }
        public string sem_display { get; set; }
        public int semester_name { get; set; }
        public int sem_year { get; set; }
        public int active_status { get; set; }
    
        public virtual university_master university_master { get; set; }
    }
}
