//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_discount_master
    {
        public long discount_id { get; set; }
        public string discount_code { get; set; }
        public string discount_name { get; set; }
        public string discount_desc { get; set; }
        public System.DateTime discount_expiryon { get; set; }
        public int discount_extend_days { get; set; }
        public decimal discount_price { get; set; }
        public int active_status { get; set; }
    }
}
