//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subject_master()
        {
            this.department_subject_mapping = new HashSet<department_subject_mapping>();
            this.device_preidentification = new HashSet<device_preidentification>();
            this.subject_master_history = new HashSet<subject_master_history>();
            this.package_details = new HashSet<package_details>();
            this.subject_unit_master = new HashSet<subject_unit_master>();
            this.college_installation_expiry = new HashSet<college_installation_expiry>();
            this.college_subject_mapping = new HashSet<college_subject_mapping>();
        }
    
        public long subject_id { get; set; }
        public string subject_code { get; set; }
        public string univ_subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_cover_path { get; set; }
        public string subject_description { get; set; }
        public int active_status { get; set; }
        public Nullable<int> rule_id { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<System.DateTime> released_on { get; set; }
        public int UniversityID { get; set; }
        public int having_questionpaper { get; set; }
        public string subject_version { get; set; }
        public int active_duration_days { get; set; }
        public System.DateTime active_duration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department_subject_mapping> department_subject_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device_preidentification> device_preidentification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_master_history> subject_master_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_details> package_details { get; set; }
        public virtual university_master university_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_unit_master> subject_unit_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<college_installation_expiry> college_installation_expiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<college_subject_mapping> college_subject_mapping { get; set; }
    }
}
