//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int fb_id { get; set; }
        public string name { get; set; }
        public string college_name { get; set; }
        public string subject_name { get; set; }
        public string mobile_number { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public System.DateTime createdon { get; set; }
        public bool isread { get; set; }
        public Nullable<System.DateTime> readon { get; set; }
        public bool status { get; set; }
        public int read_by { get; set; }
    }
}
