//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_session_track
    {
        public long user_session_track_id { get; set; }
        public string session_id { get; set; }
        public long user_id { get; set; }
        public string visit_page_url { get; set; }
        public int repeated_visit_count { get; set; }
        public System.DateTime visited_on { get; set; }
        public System.DateTime visited_time { get; set; }
    }
}
