//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class college_group_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public college_group_master()
        {
            this.college_group_map = new HashSet<college_group_map>();
        }
    
        public int college_group_id { get; set; }
        public string college_group_name { get; set; }
        public string college_group_desc { get; set; }
        public int active_status { get; set; }
        public System.DateTime enter_on { get; set; }
        public int enter_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<college_group_map> college_group_map { get; set; }
    }
}
