//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_feedback
    {
        public int user_feedback_id { get; set; }
        public long user_id { get; set; }
        public string feedback { get; set; }
        public System.DateTime feedback_on { get; set; }
        public int feedback_category { get; set; }
    
        public virtual user_master user_master { get; set; }
    }
}
