//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public business_customer()
        {
            this.product_request_master_history = new HashSet<product_request_master_history>();
            this.product_request_master = new HashSet<product_request_master>();
            this.product_request_master1 = new HashSet<product_request_master>();
            this.product_request_master_history1 = new HashSet<product_request_master_history>();
        }
    
        public long bcust_id { get; set; }
        public string bcust_first_name { get; set; }
        public string bcust_name { get; set; }
        public string bcust_password { get; set; }
        public int role_id { get; set; }
        public string bcust_email_id { get; set; }
        public long bcust_mobile { get; set; }
        public Nullable<int> loggedin_status { get; set; }
        public Nullable<System.DateTime> last_loggedin_date { get; set; }
        public int is_first_login { get; set; }
        public int active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public string bcust_profileimage { get; set; }
        public string bcust_address { get; set; }
        public Nullable<int> state_id { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string phonenumber { get; set; }
        public bool Bulk_mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master_history> product_request_master_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master> product_request_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master> product_request_master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master_history> product_request_master_history1 { get; set; }
    }
}
