//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_enc
    {
        public long subject_encid { get; set; }
        public int subject_id { get; set; }
        public string enc_data { get; set; }
        public System.DateTime generated_on { get; set; }
    }
}
