//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_cancel_history
    {
        public int order_cancel_id { get; set; }
        public string order_ref_no { get; set; }
        public int cancelled_by { get; set; }
        public System.DateTime cancelled_on { get; set; }
        public string category { get; set; }
        public string reason { get; set; }
    }
}
