//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_master_history
    {
        public long subject_historyid { get; set; }
        public long subject_id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_cover_path { get; set; }
        public string subject_description { get; set; }
        public int active_status { get; set; }
        public int rule_id { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<System.DateTime> released_on { get; set; }
        public int UniversityID { get; set; }
        public int having_questionpaper { get; set; }
        public string subject_version { get; set; }
        public int active_duration_days { get; set; }
        public System.DateTime active_duration_date { get; set; }
    
        public virtual subject_master subject_master { get; set; }
        public virtual university_master university_master { get; set; }
    }
}
