//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_cart_details
    {
        public long user_cart_details_id { get; set; }
        public long user_id { get; set; }
        public int package_id { get; set; }
        public Nullable<int> delivery_modeid { get; set; }
        public System.DateTime created_on { get; set; }
        public string package_display_name { get; set; }
    
        public virtual package_master package_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
