//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_activationmaster
    {
        public long activationmasterid { get; set; }
        public Nullable<long> user_subscribed_masterid { get; set; }
        public Nullable<long> buyer_userid { get; set; }
        public Nullable<long> buyer_mobileNo { get; set; }
        public string activationcode { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> created_userid { get; set; }
        public Nullable<long> activated_userid { get; set; }
        public Nullable<System.DateTime> activated_date { get; set; }
        public Nullable<int> activationstatus { get; set; }
    }
}
