//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_preidentification
    {
        public long device_preidentification_id { get; set; }
        public string device_id { get; set; }
        public long subject_id { get; set; }
        public int expiry_days { get; set; }
        public int enter_by { get; set; }
        public System.DateTime enter_on { get; set; }
    
        public virtual subject_master subject_master { get; set; }
    }
}
