//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_details
    {
        public int package_detail_id { get; set; }
        public int package_id { get; set; }
        public long subject_id { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
        public int validity_days { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> subject_unit_type { get; set; }
    
        public virtual subject_master subject_master { get; set; }
        public virtual package_master package_master { get; set; }
    }
}
