//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_poll_userreply
    {
        public long feedback_poll_userreply_id { get; set; }
        public int feedback_poll_qanswer1 { get; set; }
        public int feedback_poll_qanswer2 { get; set; }
        public int feedback_poll_qanswer3 { get; set; }
        public int feedback_poll_qanswer4 { get; set; }
        public int feedback_poll_qanswer5 { get; set; }
        public string uname { get; set; }
        public Nullable<long> mobile { get; set; }
        public string email_id { get; set; }
        public System.DateTime polled_on { get; set; }
    
        public virtual feedback_poll_userreply feedback_poll_userreply1 { get; set; }
        public virtual feedback_poll_userreply feedback_poll_userreply2 { get; set; }
    }
}
