//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subject_mapping
    {
        public long user_subject_id { get; set; }
        public int subject_id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_version { get; set; }
        public string subject_cover_path { get; set; }
        public System.DateTime subject_purchasedon { get; set; }
        public int user_id { get; set; }
        public int department_id { get; set; }
        public string department_code { get; set; }
        public string department_name { get; set; }
        public Nullable<int> download_status { get; set; }
        public System.DateTime downloaded_on { get; set; }
        public int subject_unit_id { get; set; }
        public string subject_unit_code { get; set; }
        public string subject_unit_name { get; set; }
        public string subject_unit_version { get; set; }
        public string subject_unit_user_version { get; set; }
        public System.DateTime subject_unit_expiryon { get; set; }
        public Nullable<System.DateTime> subject_trial_expiryon { get; set; }
        public Nullable<int> is_trial { get; set; }
        public Nullable<int> is_demo { get; set; }
        public int is_unit_or_index { get; set; }
        public string subject_unit_path { get; set; }
        public int is_updated_to_client { get; set; }
        public Nullable<System.DateTime> last_modified_on { get; set; }
        public Nullable<System.DateTime> last_client_updated_on { get; set; }
        public Nullable<int> is_updated_subunit_to_client { get; set; }
        public Nullable<System.DateTime> last_subunit_modified_on { get; set; }
        public Nullable<System.DateTime> last_subunit_client_updated_on { get; set; }
        public System.DateTime package_expirydate { get; set; }
        public Nullable<int> is_purchased { get; set; }
        public Nullable<int> yearsem { get; set; }
    }
}
