//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class regulation
    {
        public int rule_id { get; set; }
        public string rule_name { get; set; }
        public string rule_desc { get; set; }
        public byte active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
