//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_app_subject_read_history
    {
        public long user_app_read_history_id { get; set; }
        public int subject_id { get; set; }
        public int total_hours { get; set; }
        public System.DateTime usage_date { get; set; }
    }
}
