//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subunit_download_history
    {
        public long user_unit_download_history { get; set; }
        public long user_id { get; set; }
        public long subject_unit_id { get; set; }
        public System.DateTime downloaded_on { get; set; }
    
        public virtual subject_unit_master subject_unit_master { get; set; }
    }
}
