//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mastercopy_usage_details
    {
        public int mastercopy_usage_id { get; set; }
        public string user_name { get; set; }
        public string email_id { get; set; }
        public Nullable<long> mobile { get; set; }
        public string department_name { get; set; }
        public int semester { get; set; }
        public System.DateTime requested_on { get; set; }
        public string otp_code { get; set; }
        public int is_otp_verified { get; set; }
    }
}
