//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocode_master
    {
        public long promo_id { get; set; }
        public string promo_code { get; set; }
        public string promo_name { get; set; }
        public string promo_desc { get; set; }
        public System.DateTime promo_expiryon { get; set; }
        public int promo_extend_days { get; set; }
        public decimal promo_discount_price { get; set; }
        public int active_status { get; set; }
    }
}
