//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_SubscribedUser
    {
        public long SubscriberUserID { get; set; }
        public string SubscriberName { get; set; }
        public string SubscriberCollege { get; set; }
        public string EmailID { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> SubscribedDate { get; set; }
        public string Subscriberip { get; set; }
        public string SubscriberCountry { get; set; }
        public string SubscriberRegion { get; set; }
        public string SubscriberCity { get; set; }
    }
}
