//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_random_pass_college
    {
        public long user_college_random_id { get; set; }
        public string verification_code { get; set; }
        public System.DateTime generated_time { get; set; }
        public int college_id { get; set; }
        public int action_type { get; set; }
        public int user_type { get; set; }
    }
}
