//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_address_details
    {
        public long delivery_address_id { get; set; }
        public long user_id { get; set; }
        public int address_type { get; set; }
        public string full_name { get; set; }
        public long mobile_number { get; set; }
        public string address { get; set; }
        public long pincode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int country { get; set; }
        public string landmark { get; set; }
        public int isbilling_delivery { get; set; }
        public System.DateTime created_on { get; set; }
    
        public virtual country_master country_master { get; set; }
    }
}
