//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public package_master()
        {
            this.package_details = new HashSet<package_details>();
            this.user_cart_details = new HashSet<user_cart_details>();
            this.user_subscribe_details = new HashSet<user_subscribe_details>();
        }
    
        public int package_id { get; set; }
        public string package_code { get; set; }
        public string package_display_name { get; set; }
        public string package_name { get; set; }
        public int package_duration_days { get; set; }
        public string long_desc { get; set; }
        public string short_desc { get; set; }
        public int selling_price { get; set; }
        public int actual_price { get; set; }
        public int department_id { get; set; }
        public long subject_id { get; set; }
        public long rule_id { get; set; }
        public Nullable<int> subject_unit_type { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<int> current_status { get; set; }
        public int activestatus { get; set; }
        public int is_offer_package { get; set; }
        public string cover_path { get; set; }
        public int univ_id { get; set; }
        public int year { get; set; }
        public int semester { get; set; }
        public int is_bundle { get; set; }
        public string keywords { get; set; }
        public string package_video_url { get; set; }
        public Nullable<int> os_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_details> package_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_cart_details> user_cart_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subscribe_details> user_subscribe_details { get; set; }
    }
}
