//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_year_master
    {
        public int batch_year_id { get; set; }
        public string batch_year { get; set; }
        public string batch_desc { get; set; }
        public int active_status { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
