//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_customer_teams
    {
        public int bcust_teamid { get; set; }
        public Nullable<long> bcust_id { get; set; }
        public string bteamCode { get; set; }
        public string bteamName { get; set; }
        public string bteamLeadName { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> active_status { get; set; }
    }
}
