//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancel_category_master
    {
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string category_desc { get; set; }
        public int active_status { get; set; }
    }
}
