//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class college_group_map
    {
        public long college_group_map_id { get; set; }
        public int college_id { get; set; }
        public int college_group_id { get; set; }
        public System.DateTime enter_on { get; set; }
        public int enter_by { get; set; }
    
        public virtual college_master college_master { get; set; }
        public virtual college_group_master college_group_master { get; set; }
    }
}
