//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class college_installation_expiry
    {
        public long college_installation_expiry_id { get; set; }
        public long college_install_id { get; set; }
        public int department_id { get; set; }
        public long subject_id { get; set; }
        public Nullable<int> install_by { get; set; }
        public Nullable<System.DateTime> installed_on { get; set; }
        public System.DateTime expiry_on { get; set; }
        public Nullable<int> semester { get; set; }
    
        public virtual college_installation_details college_installation_details { get; set; }
        public virtual department_master department_master { get; set; }
        public virtual subject_master subject_master { get; set; }
    }
}
