//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class college_test_installation_details
    {
        public long college_test_install_id { get; set; }
        public int college_id { get; set; }
        public string installation_centre_name { get; set; }
        public string primary_mac { get; set; }
        public System.DateTime enter_on { get; set; }
        public long enter_by { get; set; }
        public int active_status { get; set; }
    }
}
