//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class college_subject_test_mapping
    {
        public long college_subject_test_mapping_id { get; set; }
        public Nullable<int> university_id { get; set; }
        public Nullable<int> college_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<long> subject_id { get; set; }
        public Nullable<int> rule_id { get; set; }
        public Nullable<int> map_year { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> active_duration_days { get; set; }
        public Nullable<System.DateTime> active_duration_date { get; set; }
    }
}
