//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department_master()
        {
            this.product_request_master_history = new HashSet<product_request_master_history>();
            this.product_request_master = new HashSet<product_request_master>();
            this.product_request_master1 = new HashSet<product_request_master>();
            this.product_request_master_history1 = new HashSet<product_request_master_history>();
            this.department_subject_mapping = new HashSet<department_subject_mapping>();
            this.college_installation_expiry = new HashSet<college_installation_expiry>();
            this.college_subject_mapping = new HashSet<college_subject_mapping>();
            this.user_master = new HashSet<user_master>();
            this.tbl_Student_user_master = new HashSet<tbl_Student_user_master>();
        }
    
        public int department_id { get; set; }
        public string department_code { get; set; }
        public string department_name { get; set; }
        public int no_of_year { get; set; }
        public int max_semester_per_year { get; set; }
        public int active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public int UniversityID { get; set; }
        public string dept_img_path { get; set; }
        public Nullable<int> coursehours { get; set; }
        public Nullable<int> visuals { get; set; }
        public Nullable<int> pagecontent { get; set; }
        public Nullable<int> solvedproblem { get; set; }
        public Nullable<int> multichoice { get; set; }
        public string dept_video { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master_history> product_request_master_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master> product_request_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master> product_request_master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_request_master_history> product_request_master_history1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department_subject_mapping> department_subject_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<college_installation_expiry> college_installation_expiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<college_subject_mapping> college_subject_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_master> user_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Student_user_master> tbl_Student_user_master { get; set; }
    }
}
