//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_subject_mapping
    {
        public int department_subject_mapping_id { get; set; }
        public int department_id { get; set; }
        public long subject_id { get; set; }
        public int rule_id { get; set; }
        public int university_id { get; set; }
        public int map_year { get; set; }
        public int semester { get; set; }
        public int active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
    
        public virtual department_master department_master { get; set; }
        public virtual subject_master subject_master { get; set; }
    }
}
