//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionID { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionMessage { get; set; }
        public string ExceptionSource { get; set; }
        public string ExceptionURL { get; set; }
        public string TargetSiteModule { get; set; }
        public string TargetSiteName { get; set; }
        public string StackTrace { get; set; }
        public string HelpLink { get; set; }
        public Nullable<bool> isFromController { get; set; }
        public System.DateTime ExceptionDate { get; set; }
        public Nullable<int> ErrorColumnNumber { get; set; }
        public Nullable<int> errorLine { get; set; }
    }
}
