//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class learnengg_payment_portal_entities : DbContext
    {
        public learnengg_payment_portal_entities()
            : base("name=learnengg_payment_portal_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<business_customer> business_customer { get; set; }
        public virtual DbSet<business_customer_teams> business_customer_teams { get; set; }
        public virtual DbSet<clienttool_user_version> clienttool_user_version { get; set; }
        public virtual DbSet<clienttool_version> clienttool_version { get; set; }
        public virtual DbSet<college_master> college_master { get; set; }
        public virtual DbSet<country_master> country_master { get; set; }
        public virtual DbSet<Demo_SubscribedUser> Demo_SubscribedUser { get; set; }
        public virtual DbSet<department_master> department_master { get; set; }
        public virtual DbSet<department_subject_mapping> department_subject_mapping { get; set; }
        public virtual DbSet<device_preidentification> device_preidentification { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<feedback_poll_userreply> feedback_poll_userreply { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuPrivilege> MenuPrivileges { get; set; }
        public virtual DbSet<product_request_master> product_request_master { get; set; }
        public virtual DbSet<product_request_master_history> product_request_master_history { get; set; }
        public virtual DbSet<promo_discount_master> promo_discount_master { get; set; }
        public virtual DbSet<promo_package_mapping> promo_package_mapping { get; set; }
        public virtual DbSet<promocode_master> promocode_master { get; set; }
        public virtual DbSet<purchase_activationmaster> purchase_activationmaster { get; set; }
        public virtual DbSet<regulation> regulations { get; set; }
        public virtual DbSet<regulation_master> regulation_master { get; set; }
        public virtual DbSet<state_master> state_master { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<subject_enc> subject_enc { get; set; }
        public virtual DbSet<subject_master> subject_master { get; set; }
        public virtual DbSet<subject_master_history> subject_master_history { get; set; }
        public virtual DbSet<subject_unit_master_history> subject_unit_master_history { get; set; }
        public virtual DbSet<Transaction_Details> Transaction_Details { get; set; }
        public virtual DbSet<univ_semester_master> univ_semester_master { get; set; }
        public virtual DbSet<user_address_details> user_address_details { get; set; }
        public virtual DbSet<user_app_subject_read_history> user_app_subject_read_history { get; set; }
        public virtual DbSet<user_cart_details> user_cart_details { get; set; }
        public virtual DbSet<user_feedback> user_feedback { get; set; }
        public virtual DbSet<user_master_history> user_master_history { get; set; }
        public virtual DbSet<user_notification_details> user_notification_details { get; set; }
        public virtual DbSet<user_notification_master> user_notification_master { get; set; }
        public virtual DbSet<user_random_pass> user_random_pass { get; set; }
        public virtual DbSet<user_subject_mapping_history> user_subject_mapping_history { get; set; }
        public virtual DbSet<user_subject_read_history_androidapp> user_subject_read_history_androidapp { get; set; }
        public virtual DbSet<user_subject_unit_read_history> user_subject_unit_read_history { get; set; }
        public virtual DbSet<user_subject_unit_read_history_androidapp> user_subject_unit_read_history_androidapp { get; set; }
        public virtual DbSet<user_subject_video_history> user_subject_video_history { get; set; }
        public virtual DbSet<user_subject_video_history_androidapp> user_subject_video_history_androidapp { get; set; }
        public virtual DbSet<user_subscribe_delivery_mode> user_subscribe_delivery_mode { get; set; }
        public virtual DbSet<user_subscribe_details> user_subscribe_details { get; set; }
        public virtual DbSet<user_subscribe_master> user_subscribe_master { get; set; }
        public virtual DbSet<user_subscribe_order_track> user_subscribe_order_track { get; set; }
        public virtual DbSet<user_subunit_download_history> user_subunit_download_history { get; set; }
        public virtual DbSet<user_wishlist> user_wishlist { get; set; }
        public virtual DbSet<user_subject_unit_read_history_restore> user_subject_unit_read_history_restore { get; set; }
        public virtual DbSet<user_login_track> user_login_track { get; set; }
        public virtual DbSet<user_session_track> user_session_track { get; set; }
        public virtual DbSet<package_details> package_details { get; set; }
        public virtual DbSet<user_subject_mapping> user_subject_mapping { get; set; }
        public virtual DbSet<university_master> university_master { get; set; }
        public virtual DbSet<user_subject_activation_history> user_subject_activation_history { get; set; }
        public virtual DbSet<package_master_track> package_master_track { get; set; }
        public virtual DbSet<user_university_privilege> user_university_privilege { get; set; }
        public virtual DbSet<package_master> package_master { get; set; }
        public virtual DbSet<subject_unit_master> subject_unit_master { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<cancel_category_master> cancel_category_master { get; set; }
        public virtual DbSet<order_cancel_history> order_cancel_history { get; set; }
        public virtual DbSet<order_cancel_random_pass> order_cancel_random_pass { get; set; }
        public virtual DbSet<user_trial_subject> user_trial_subject { get; set; }
        public virtual DbSet<payment_master> payment_master { get; set; }
        public virtual DbSet<batch_year_master> batch_year_master { get; set; }
        public virtual DbSet<sms_batch_data> sms_batch_data { get; set; }
        public virtual DbSet<payment_refund_master> payment_refund_master { get; set; }
        public virtual DbSet<college_installation_details> college_installation_details { get; set; }
        public virtual DbSet<mastercopy_usage_details> mastercopy_usage_details { get; set; }
        public virtual DbSet<college_installation_expiry> college_installation_expiry { get; set; }
        public virtual DbSet<user_random_pass_college> user_random_pass_college { get; set; }
        public virtual DbSet<college_subject_mapping> college_subject_mapping { get; set; }
        public virtual DbSet<college_test_installation_details> college_test_installation_details { get; set; }
        public virtual DbSet<college_test_installation_expiry> college_test_installation_expiry { get; set; }
        public virtual DbSet<college_subject_test_mapping> college_subject_test_mapping { get; set; }
        public virtual DbSet<college_group_map> college_group_map { get; set; }
        public virtual DbSet<user_feedback_master> user_feedback_master { get; set; }
        public virtual DbSet<college_group_master> college_group_master { get; set; }
        public virtual DbSet<user_master> user_master { get; set; }
        public virtual DbSet<user_subject_read_history> user_subject_read_history { get; set; }
        public virtual DbSet<student_user_random_pass> student_user_random_pass { get; set; }
        public virtual DbSet<Student_subject_unit_read_history> Student_subject_unit_read_history { get; set; }
        public virtual DbSet<Student_subject_read_history> Student_subject_read_history { get; set; }
        public virtual DbSet<tbl_Student_user_master> tbl_Student_user_master { get; set; }
    
        public virtual ObjectResult<string> ImportExcel(string fileLocation, string fileextension)
        {
            var fileLocationParameter = fileLocation != null ?
                new ObjectParameter("fileLocation", fileLocation) :
                new ObjectParameter("fileLocation", typeof(string));
    
            var fileextensionParameter = fileextension != null ?
                new ObjectParameter("fileextension", fileextension) :
                new ObjectParameter("fileextension", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ImportExcel", fileLocationParameter, fileextensionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ImportExcel1(string fileLocation, string fileextension)
        {
            var fileLocationParameter = fileLocation != null ?
                new ObjectParameter("fileLocation", fileLocation) :
                new ObjectParameter("fileLocation", typeof(string));
    
            var fileextensionParameter = fileextension != null ?
                new ObjectParameter("fileextension", fileextension) :
                new ObjectParameter("fileextension", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ImportExcel1", fileLocationParameter, fileextensionParameter);
        }
    }
}
