//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.MenuPrivileges = new HashSet<MenuPrivilege>();
        }
    
        public int MenuID { get; set; }
        public int ParentMenuID { get; set; }
        public string MenuText { get; set; }
        public string TargetURL { get; set; }
        public int MenuLevel { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<bool> active_status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> Univ_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPrivilege> MenuPrivileges { get; set; }
    }
}
