//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPrivilege
    {
        public int MenuPrivilegeID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int MenuID { get; set; }
        public Nullable<bool> active_status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual user_role user_role { get; set; }
    }
}
