//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_cancel_random_pass
    {
        public long user_random_id { get; set; }
        public int buyer_user_id { get; set; }
        public string order_ref_no { get; set; }
        public long buyer_mobile { get; set; }
        public string verification_code { get; set; }
        public int action_user_id { get; set; }
        public System.DateTime generated_time { get; set; }
        public int action_type { get; set; }
        public Nullable<int> user_type { get; set; }
    }
}
