//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_master_track
    {
        public long package_master_track_id { get; set; }
        public long user_id { get; set; }
        public string previous_words { get; set; }
        public string current_words { get; set; }
        public int type { get; set; }
        public int package_id { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
