//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_refund_master
    {
        public long payment_refund_master_id { get; set; }
        public long user_subscribe_master_id { get; set; }
        public string Txn_msg { get; set; }
        public string Txn_err_msg { get; set; }
        public string ClintTxnRefNo { get; set; }
        public string TPSLRefundID { get; set; }
        public string request_token { get; set; }
        public decimal refund_amt { get; set; }
        public System.DateTime refund_date { get; set; }
        public long refund_by { get; set; }
    
        public virtual user_subscribe_master user_subscribe_master { get; set; }
    }
}
