//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_request_master
    {
        public int request_id { get; set; }
        public long bcust_id { get; set; }
        public int college_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> product_count { get; set; }
        public string remarks { get; set; }
        public int active_status { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<int> bcustTeam_id { get; set; }
    
        public virtual business_customer business_customer { get; set; }
        public virtual business_customer business_customer1 { get; set; }
        public virtual college_master college_master { get; set; }
        public virtual college_master college_master1 { get; set; }
        public virtual department_master department_master { get; set; }
        public virtual department_master department_master1 { get; set; }
    }
}
