//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_package_mapping
    {
        public long promo_package_id { get; set; }
        public long promo_id { get; set; }
        public long package_id { get; set; }
        public int active_status { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
