//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_batch_data
    {
        public long sem_data_id { get; set; }
        public long mobile { get; set; }
        public int batch_year_id { get; set; }
        public int year { get; set; }
        public int university_id { get; set; }
    }
}
