//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_subject_unit_read_history
    {
        public long Student_read_unit_history_id { get; set; }
        public int Student_id { get; set; }
        public int subject_id { get; set; }
        public string subject_unitid { get; set; }
        public int total_seconds { get; set; }
        public System.DateTime subject_read_start { get; set; }
        public System.DateTime subject_read_stop { get; set; }
        public Nullable<int> is_updated_to_server { get; set; }
        public int read_percentage { get; set; }
    }
}
