//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_unit_master_history
    {
        public long unit_history_id { get; set; }
        public long unit_id { get; set; }
        public string unit_code { get; set; }
        public string unit_name { get; set; }
        public long subject_id { get; set; }
        public int active_status { get; set; }
        public string subject_unit_path { get; set; }
        public Nullable<int> is_demo { get; set; }
        public Nullable<int> is_unit_or_index { get; set; }
        public string subject_unit_version { get; set; }
        public Nullable<System.DateTime> released_on { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> filesize_in_mb { get; set; }
        public Nullable<int> created_by { get; set; }
    }
}
