//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_user_master
    {
        public long Student_user_id { get; set; }
        public string user_first_name { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public string email_id { get; set; }
        public long mobile { get; set; }
        public Nullable<int> loggedin_status { get; set; }
        public Nullable<System.DateTime> last_loggedin_date { get; set; }
        public int is_first_login { get; set; }
        public int active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public string profileimage { get; set; }
        public Nullable<int> univ_id { get; set; }
        public Nullable<int> collegeid { get; set; }
        public string collegename { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string department_name { get; set; }
        public Nullable<int> currentyear { get; set; }
        public Nullable<int> currentsemester { get; set; }
        public string address { get; set; }
        public Nullable<int> state_id { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string phonenumber { get; set; }
        public Nullable<bool> Bulk_mail { get; set; }
        public string primary_imei { get; set; }
        public string primary_mac { get; set; }
        public string tool_version_name { get; set; }
        public Nullable<int> registered_from { get; set; }
        public string roll_number { get; set; }
        public Nullable<long> ref_mobileno { get; set; }
        public string primary_andriod_mac { get; set; }
        public Nullable<int> college_group_id { get; set; }
        public string AcademicYear { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> LockoutEndTime { get; set; }
    
        public virtual college_master college_master { get; set; }
        public virtual department_master department_master { get; set; }
        public virtual user_role user_role { get; set; }
        public virtual university_master university_master { get; set; }
    }
}
