//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subscribe_delivery_mode
    {
        public int user_subscribe_delivery_mode_id { get; set; }
        public string subscribe_delivery_mode { get; set; }
        public string description { get; set; }
        public int price { get; set; }
        public int active_status { get; set; }
        public Nullable<int> product_price { get; set; }
        public Nullable<int> delivery_price { get; set; }
        public Nullable<int> delivery_type { get; set; }
        public string delivery_desc { get; set; }
    }
}
