//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_university_privilege
    {
        public long univ_user_privilege_id { get; set; }
        public int university_id { get; set; }
        public long user_id { get; set; }
        public int active_status { get; set; }
        public System.DateTime mapped_on { get; set; }
        public long mapped_by { get; set; }
    
        public virtual university_master university_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
