//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subject_mapping_history
    {
        public long user_subject_history_id { get; set; }
        public long user_subject_id { get; set; }
        public int subject_id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_version { get; set; }
        public string subject_cover_path { get; set; }
        public int user_id { get; set; }
        public int department_id { get; set; }
        public string department_code { get; set; }
        public string department_name { get; set; }
        public Nullable<int> download_status { get; set; }
        public System.DateTime downloaded_on { get; set; }
        public int subject_unit_id { get; set; }
        public string subject_unit_code { get; set; }
        public string subject_unit_name { get; set; }
        public string subject_unit_version { get; set; }
        public System.DateTime subject_unit_expiryon { get; set; }
        public Nullable<int> is_demo { get; set; }
        public Nullable<int> is_unit_or_index { get; set; }
        public string subject_unit_path { get; set; }
    }
}
