//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_notification_master
    {
        public int notification_id { get; set; }
        public string notification_message { get; set; }
        public int notification_for { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
