//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subscribe_details
    {
        public long user_subscribe_details_id { get; set; }
        public long user_subscribe_master_id { get; set; }
        public int package_id { get; set; }
        public int actual_price { get; set; }
        public int selling_price { get; set; }
        public int package_validity_days { get; set; }
        public System.DateTime package_expiryon { get; set; }
        public Nullable<long> promocode_id { get; set; }
        public Nullable<int> promo_discount_amt { get; set; }
        public Nullable<int> deliver_status { get; set; }
    
        public virtual user_subscribe_master user_subscribe_master { get; set; }
        public virtual package_master package_master { get; set; }
    }
}
