//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subject_read_history
    {
        public long user_read_history_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public int subject_id { get; set; }
        public int total_hours { get; set; }
        public System.DateTime last_read_on { get; set; }
        public Nullable<int> is_updated_to_server { get; set; }
        public string hours_topic_video { get; set; }
        public Nullable<System.DateTime> entered_on { get; set; }
    }
}
