//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subject_activation_history
    {
        public long user_subject_activation_id { get; set; }
        public int subject_id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_version { get; set; }
        public int user_id { get; set; }
        public int department_id { get; set; }
        public System.DateTime subject_expiry_date { get; set; }
        public System.DateTime subject_expiry_extension_date { get; set; }
        public int subject_extension_days { get; set; }
        public System.DateTime activated_on { get; set; }
        public int activated_by { get; set; }
        public int activation_type { get; set; }
        public int activation_product_type { get; set; }
    }
}
