//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master_history
    {
        public long user_historyid { get; set; }
        public long user_id { get; set; }
        public string user_first_name { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public string email_id { get; set; }
        public long mobile { get; set; }
        public Nullable<int> loggedin_status { get; set; }
        public Nullable<System.DateTime> last_loggedin_date { get; set; }
        public int is_first_login { get; set; }
        public int active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<int> univ_id { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string address { get; set; }
        public Nullable<int> state_id { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string phonenumber { get; set; }
        public bool Bulk_mail { get; set; }
        public string primary_imei { get; set; }
        public string primary_mac { get; set; }
    
        public virtual user_master user_master { get; set; }
    }
}
