//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_role()
        {
            this.MenuPrivileges = new HashSet<MenuPrivilege>();
            this.user_master = new HashSet<user_master>();
            this.tbl_Student_user_master = new HashSet<tbl_Student_user_master>();
        }
    
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string role_desc { get; set; }
        public int role_type { get; set; }
        public int active_subject_days { get; set; }
        public int active_status { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public string LandingPage { get; set; }
        public Nullable<int> role_level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPrivilege> MenuPrivileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_master> user_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Student_user_master> tbl_Student_user_master { get; set; }
    }
}
