//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_trial_subject
    {
        public long user_trial_subject_id { get; set; }
        public long user_id { get; set; }
        public long subject_id { get; set; }
        public System.DateTime trail_expiry_on { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
