//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subscribe_order_track
    {
        public long user_subscribe_order_track_id { get; set; }
        public long user_subscribe_master_id { get; set; }
        public Nullable<int> package_id { get; set; }
        public long orderby { get; set; }
        public int orderstatus { get; set; }
        public System.DateTime orderon { get; set; }
        public string orderrefno { get; set; }
        public string ordermobile { get; set; }
        public int preparedstatus { get; set; }
        public Nullable<System.DateTime> preparedon { get; set; }
        public Nullable<long> preparedby { get; set; }
        public string preparedcomments { get; set; }
        public int qualitycheckstatus { get; set; }
        public Nullable<System.DateTime> qualitycheckon { get; set; }
        public Nullable<long> qualitycheckby { get; set; }
        public string qualitycheckcomments { get; set; }
        public int deliverstatus { get; set; }
        public Nullable<System.DateTime> deliveron { get; set; }
        public string deliverby { get; set; }
        public string delivercomments { get; set; }
        public string couriername { get; set; }
        public string courierrefno { get; set; }
        public string couriercontactno { get; set; }
        public Nullable<int> expecteddeliverywdays { get; set; }
        public Nullable<long> denterby { get; set; }
        public Nullable<System.DateTime> denteron { get; set; }
        public int paystatus { get; set; }
        public Nullable<System.DateTime> payreceiveon { get; set; }
        public Nullable<long> payreceivedby { get; set; }
        public Nullable<long> payreceivedamt { get; set; }
        public Nullable<System.DateTime> payenteron { get; set; }
        public int activationstatus { get; set; }
        public Nullable<System.DateTime> activationon { get; set; }
        public Nullable<long> activationby { get; set; }
        public string activationmobile { get; set; }
        public Nullable<int> refundstatus { get; set; }
        public Nullable<System.DateTime> refundon { get; set; }
        public Nullable<int> refundamt { get; set; }
        public Nullable<long> refundby { get; set; }
    
        public virtual user_subscribe_master user_subscribe_master { get; set; }
    }
}
