//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_feedback_master
    {
        public long user_feedback_id { get; set; }
        public string user_name { get; set; }
        public string rolle_desc { get; set; }
        public int rolle_id { get; set; }
        public Nullable<int> mobile { get; set; }
        public string email { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<int> college_id { get; set; }
        public string feedback { get; set; }
        public System.DateTime enter_on { get; set; }
    }
}
