//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odishadtet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subscribe_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_subscribe_master()
        {
            this.user_subscribe_details = new HashSet<user_subscribe_details>();
            this.user_subscribe_order_track = new HashSet<user_subscribe_order_track>();
            this.payment_refund_master = new HashSet<payment_refund_master>();
        }
    
        public long user_subscribe_master_id { get; set; }
        public long user_id { get; set; }
        public string payment_ref_no { get; set; }
        public int count { get; set; }
        public Nullable<long> discount_id { get; set; }
        public Nullable<int> discount_amt { get; set; }
        public int TransactionType { get; set; }
        public int payment_status { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<int> user_subscribe_delivery_mode_id { get; set; }
        public System.DateTime payment_on { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<long> billing_address_id { get; set; }
        public Nullable<long> deliver_address_id { get; set; }
        public Nullable<System.DateTime> refund_on { get; set; }
        public Nullable<int> refund_amount { get; set; }
        public Nullable<long> refund_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subscribe_details> user_subscribe_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subscribe_order_track> user_subscribe_order_track { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_refund_master> payment_refund_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
